name: RUN puppeteer

on:
  push:
    branches: [ main2 ]

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install command
      run: npm i

    - name: RUN app.js
      env:
        DATABASE: ${{ secrets.DATABASE }}
        HOST: ${{ secrets.HOST }}
        PASSWORD: ${{ secrets.PASSWORD }}
        USER: ${{ secrets.USER }}
      run: node app.js
