name: RUN puppeteer

on:
  push:
    branches: [ main2 ]

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install command
      run: npm i puppeteer mysql2 dotenv

    - name: RUN app.js
      env:
        DATABASE100: ${{ secrets.DATABASE }}
        HOST100: ${{ secrets.HOST }}
        PASSWORD100: ${{ secrets.PASSWORD }}
        USER100: ${{ secrets.USER }}
      run: node app.js
